github = "https://github.com/oknozor/rosa-parse"
changelog_path = "CHANGELOG.md"

authors = [
    { signature = "Paul Delafosse", username = "oknozor" },
]

pre_bump_hooks = [
    "cargo test",
    "cargo clippy",
    "cargo fmt --all",
    "cargo bump %version",
]

post_bump_hooks = [
    "git push origin %version",
    "cargo publish",
]
